#!/usr/bin/env ruby
# frozen_string_literal: true

Signal.trap('INT') { exit(130) }
Signal.trap('SIGINT') { exit(130) }
Signal.trap('TERM') { exit(143) }

require 'bundler/setup'

require 'biscotti'

require 'optparse'

require 'awesome_print'

word = 'tango'.split('').sort.freeze

ap word

# OptionParser.new do |opts|
#   opts.banner = 'Usage: bundle exec biscotti [OPTION]... [FILE]'

#   opts.on('-V', '--version', 'Print version info') do
#     $stdout.puts(Biscotti::VERSION)
#     exit(0)
#   end

#   opts.on_tail('-h', '--help', 'Show this message') do
#     warn(opts)
#     exit(0)
#   end
# end.parse!

# raise 'File not processable' unless Sodor::CLI.processable?

begin
rescue Errno::EPIPE
  exit(74)
end
